[package]
name = "XML-Magic"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
xml-rs = "0.8"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }